<a href="https://colab.research.google.com/github/SourabhThanvi/Pw_Skills_Sourabh/blob/main/Numpy_Numerical_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [6]:
arr = np.random.randint(1,100, (3,3))

In [7]:
arr

array([[17, 13, 69],
       [ 9, 99, 75],
       [ 7, 89, 60]])

In [8]:
arr.T

array([[17,  9,  7],
       [13, 99, 89],
       [69, 75, 60]])

## 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [10]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
## Another way of creating a 1D Numpy array of 10 elements
array = np.linspace(1,100, 10, dtype=int)
array

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [11]:
arr2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
arr2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [20]:
arr3 = np.random.random_sample((4, 4))*100

In [29]:
# Errored Code (Tried Code)

# np.repeat(arr3, 2, axis=0)
# np.repeat(arr3, 2, axis=0)

# Learned from documentation
np.pad(arr3, pad_width=1, constant_values=0)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        , 30.07877425, 83.84587067, 94.10633652, 26.89616287,
         0.        ],
       [ 0.        , 97.40040809, 89.86248064, 37.51259353, 80.09619573,
         0.        ],
       [ 0.        ,  9.18985411, 42.57720581, 65.28704655, 85.99220328,
         0.        ],
       [ 0.        , 76.49887046,  0.83371505,  1.19529801,  4.08369764,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

## 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [30]:
arr4 = np.linspace(10, 60, 5)

In [31]:
arr4

array([10. , 22.5, 35. , 47.5, 60. ])

## 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [32]:
arr5 = np.array(['python', 'numpy', 'pandas'])

In [36]:
upper_case = np.char.upper(arr5)
lower_case = np.char.lower(arr5)
title_case = np.char.title(arr5)
capital_case = np.char.capitalize(arr5)

In [37]:
print(upper_case)
print(lower_case)
print(title_case)
print(capital_case)

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']
['Python' 'Numpy' 'Pandas']


## 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [39]:
arr6 = np.array(['python', 'numpy', 'pandas'])

In [43]:
# Errored Code

# np.char.split(arr6)

np.char.join(' ',arr6)

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

## 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [44]:
arr7_1 = np.random.randint(1,10, (2,2))
arr7_2 = np.random.randint(1,10, (2,2))

In [46]:
print(arr7_1)
print(arr7_2)

[[2 9]
 [2 3]]
[[6 9]
 [3 4]]


In [45]:
print(arr7_1 + arr7_2)
print(arr7_1 - arr7_2)
print(arr7_1 * arr7_2)
print(arr7_1 / arr7_2)

[[ 8 18]
 [ 5  7]]
[[-4  0]
 [-1 -1]]
[[12 81]
 [ 6 12]]
[[0.33333333 1.        ]
 [0.66666667 0.75      ]]


## 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [51]:
arr8 = np.eye(5)

In [52]:
# Code logic where i==j i.e row and column value must be same or we can say that value of is equal to 1.

np.where(arr8 == 1)

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [53]:
arr8[arr8 == 1]

array([1., 1., 1., 1., 1.])

## 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [55]:
arr9 = np.random.randint(0, 1000, 100)

In [56]:
arr9

array([196, 348,  64, 373,  17, 273, 104, 511, 845, 828, 508, 718, 335,
       423, 352, 723, 378, 359, 735, 454, 168, 712, 361, 682, 502, 903,
       418, 191, 246, 291, 172, 751, 112, 529, 226, 318, 879, 430,  39,
       907, 310,  93, 322, 909,  60, 696,  70, 126, 856, 934, 300, 467,
       283, 891, 289, 572, 312,  87, 452, 745, 674, 236, 239,  43, 448,
       232, 481, 318, 119, 572, 710, 565, 885,  78, 827, 997, 304,  84,
       694, 159, 281, 108, 601, 921, 435,  68, 769, 695, 364, 669, 188,
       959, 730, 884,  35, 446, 820, 248, 148, 124])

In [58]:
arr9.shape

(100,)

In [59]:
def prime_num(arrays):
  for num in arrays:
    if num > 1:
      for i in range(2, num): # num is exclusive, condtion for prime num is :- num must be divisible by 1 and num itself.
        if (num % i) == 0:
          break
      else:
        print(num)

In [60]:
prime_num(arr9)

373
17
359
191
751
907
467
283
239
43
827
997
281
601
769


## 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [65]:
temp_c = np.random.randint(10, 40, 30)

In [66]:
temp_c

array([27, 18, 10, 32, 11, 18, 14, 27, 20, 25, 27, 39, 16, 21, 17, 25, 31,
       31, 23, 25, 24, 23, 24, 10, 29, 11, 30, 17, 12, 28])

In [67]:
for i in range(0, len(temp_c),7):
  print(np.mean(i))


0.0
7.0
14.0
21.0
28.0
